### ISSUE TITLE
Could not load plugin: c:\ado\plus\g\gtools_windows.plugin

### ISSUE THREAD

**Issue by dgcbritto** [mcaceresb/stata-gtools#35] opened 2018-03-06 18:55 UTC
Hi guys,

I'm trying to run gtools on a Windows Server 2016 with Stata 15, but I'm getting the following error:

Stata MP 15 6 users output:
gcollapse y, by(x)
Could not load plugin: c:\ado\plus\g\gtools_windows.plugin
(error occurred while loading _gtools_internal.ado)

Any tips on how to solve it?

Thanks a lot for this amazing command!

**Comment by mcaceresb** [comment] 2018-03-06 19:04
Can you run

```stata
!dir c:\ado\plus\g\*gtools*
!dir c:\ado\plus\s\*spooky*
```

And post the output?

**Comment by dgcbritto** [comment] 2018-03-06 19:15
. !dir c:\ado\plus\g\*gtools*

. !dir c:\ado\plus\s\*spooky*

.

I get only "." as output. Did I run it right?


________________________________
De: Mauricio Caceres Bravo <notifications@github.com>
Enviado: terça-feira, 6 de março de 2018 16:04
Para: mcaceresb/stata-gtools
Cc: dgcbritto; Author
Assunto: Re: [mcaceresb/stata-gtools] Could not load plugin: c:\ado\plus\g\gtools_windows.plugin (#35)


Can you run

!dir c:\ado\plus\g\*gtools*
!dir c:\ado\plus\s\*spooky*

And post the output?

**Comment by mcaceresb** [comment] 2018-03-06 19:17
Perhaps; I suspected the issue is that the files are missing. Can you physically navigate to those directories using file explorer? If they are indeed blank, then gtools was not installed correctly. Run

```stata
local github "https://raw.githubusercontent.com"
net install gtools, from(`github'/mcaceresb/stata-gtools/master/build/)
```

And check again using file explorer. If this does not fix the problem then it's a problem with permissions, and you'll have to install gtools in a different folder.

Run the above first. If it's a permissions issue let me know and I can guide you through that install.

**Comment by dgcbritto** [comment] 2018-03-06 19:24
I've run it but the problem remains. My user has admin privileges, I can enter all folders and modify files in C.


Do you think I should try installing in a different folder/path?

________________________________
De: Mauricio Caceres Bravo <notifications@github.com>
Enviado: terça-feira, 6 de março de 2018 16:17
Para: mcaceresb/stata-gtools
Cc: dgcbritto; Author
Assunto: Re: [mcaceresb/stata-gtools] Could not load plugin: c:\ado\plus\g\gtools_windows.plugin (#35)


Perhaps; I suspected the issue is that the files are missing. Can you physically navigate to those directories using file explorer? If they are indeed blank, then gtools was not installed correctly. Run

local github "https://raw.githubusercontent.com"
net install gtools, from(`github'/mcaceresb/stata-gtools/master/build/)

And check again using file explorer. If this does not fix the problem then it's a problem with permissions, and you'll have to install gtools in a different folder.

Run the above first. If it's a permissions issue let me know and I can guide you through that install.

**Comment by mcaceresb** [comment] 2018-03-06 20:25
You mean that the folders are blank, right? Perhaps there is a discrepancy in the ado paths. How about:

```stata
adopath
disp "`c(sysdir_plus)'"
disp "`c(sysdir_personal)'"
```

You can try and download everything manually. I have placed just the relevant files in the release page (https://github.com/mcaceresb/stata-gtools/releases). You can download `gtools-0.12.5.zip`, extract the file, and add 

```stata
adopath + /path/to/gtools
```

to your scripts.

**Comment by dgcbritto** [comment] 2018-03-07 14:58
These commands show:
. disp "`c(sysdir_plus)'"
c:\ado\plus/

. disp "`c(sysdir_personal)'"
c:\ado\personal/

I mannually removed all gtools installation files from c:/ado/plus and manually installed it from the zip file, as you said. However, I get the same error message while running gcollapse:
"Could not load plugin: c:\ado\plus\g\gtools_windows.plugin
(error occurred while loading _gtools_internal.ado)"
I've also tried to use gegen to check it was some specific problem with gcollapse, but the command gives exactly the same error.

Could it have to do with my Windows version? Windows Server 2016

**Comment by mcaceresb** [comment] 2018-03-07 15:14
You said "mannually removed all gtools installation files from c:/ado/plus"; I thought the folders were empty? Anyway, if you did it manually then yes, it might be your windows version.

To check, extract the zip in some a folder but don't move the files. For example, if you extracted them to "C:\testing\gtools" then run, from Stata,

```stata
cd C:\testing\gtools
clear
set obs 10
gen x = 1
gcollapse x
capture program drop gtools_plugin
program gtools_plugin, plugin using("gtools_windows.plugin")
```

And let me know what happens.

**Comment by dgcbritto** [comment] 2018-03-07 15:25
No, it wasn't empty before. Installation with net install was successful at first

I've run your code but continue to get the same message:
". gcollapse x
Could not load plugin: .\gtools_windows.plugin
(error occurred while loading _gtools_internal.ado)"

"gcollapse x
Could not load plugin: .\gtools_windows.plugin
(error occurred while loading _gtools_internal.ado)"

**Comment by mcaceresb** [comment] 2018-03-07 15:36
I was hoping it was just a permissions thing or an install problem, but it certainly look like it's an issue with the plugin. Hail Mary pass: If you run "disp c(bit)" from Stata, what's the answer?

I don't have access to Windows Server 2016 and I don't know why it wouldn't work there, so this will probably go unfixed for some time.

**Comment by dgcbritto** [comment] 2018-03-07 15:56
"disp c(bit)
64"

I've given another shot running it in Compatibility mode with Windows 7&8 and executing as administrator but no luck.
No worries, thanks a lot in any case. That's a great tool, severely improve work with huge datasets!

**Comment by ppoppitz** [comment] 2018-05-11 08:34
I ran into the same problem running `gegen` with Stata 15.1 on Windows Server 2016.

Gtools ado is installed in a network folder and runs fine from Linux and regular Windows Systems but fails on Windows Server. I also tried compatibility mode (win 7) without success.

Any chance to get this bug fixed. I would like to help, although I have no C++ programming skills.

**Comment by mcaceresb** [comment] 2018-05-11 19:40
1. Are you able to install programs on the server?
2. If not, does the server happen to have Cygwin and MinGW?

Hopefully this is an issue with the gtools code that I can fix rather than spookyhash. If the answer to both of the above are true, I'll try to upload some test plugins for you to try out on the server and see if we can narrow down the problem anyway.

**Comment by ppoppitz** [comment] 2018-05-16 11:19
no, to both questions. 
Will check with the IT department if they can provide an suitable environment.

**Comment by ppoppitz** [comment] 2018-05-16 11:35
ok

**Comment by ppoppitz** [comment] 2018-05-16 19:49
as expected:
```Stata
. cd
L:\Cloud\gtest

. do "L:\Cloud\gtest\test.do"

. program test1, plugin using(test1.plugin) 

. plugin call test1
Hello World

. 
. program test2, plugin using(test2.plugin) 
Could not load plugin: .\test2.plugin
r(9999);

end of do-file

r(9999);
```

**Comment by mcaceresb** [comment] 2018-05-16 19:53
Ok, then the programs I referenced above are not actually the ones required. Does you have access to  Visual Studio on the server?

**Comment by dgcbritto** [comment] 2018-05-16 20:05
I'm trying to follow too. I have access to Visual Studio.


diogo

________________________________
De: Mauricio Caceres Bravo <notifications@github.com>
Enviado: quarta-feira, 16 de maio de 2018 16:53
Para: mcaceresb/stata-gtools
Cc: dgcbritto; Author
Assunto: Re: [mcaceresb/stata-gtools] Could not load plugin: c:\ado\plus\g\gtools_windows.plugin (#35)


Ok, then the programs I referenced above are not actually the ones required. Does you have access to Visual Studio on the server?

**Comment by mcaceresb** [comment] 2018-05-16 20:16
* Can you open the  Visual Studio Developer Command Prompt? The command you will need is `msbuild`
* You will need a copy of the [spookyhash repo](https://github.com/centaurean/spookyhash).
* Last, you need [premake5](https://premake.github.io/download.html)

The steps are
```
cd spookyhash\build
premake5.exe vs2013
```

Replace `vs2013` with `vs2017` or similar depending on your version. Then open the VS Developer Command Prompt and run
```
cd spookyhash\build
msbuild SpookyHash.sln
```

This should generate a version of spookyhash.dll compatible with your system. Let me know how far you get.

**Comment by ppoppitz** [comment] 2018-05-16 20:18
sry, no visual studio

**Comment by mcaceresb** [comment] 2018-05-16 20:28
You have to download it and copy it to that location. See: https://premake.github.io/download.html ([DL link](https://github.com/premake/premake-core/releases/download/v5.0.0-alpha12/premake-5.0.0-alpha12-windows.zip)). Unzip and copy the exe to the build folder.

**Comment by mcaceresb** [comment] 2018-06-05 16:33
No worries. I'm glad it's working on your end. 

@ppoppitz was experiencing the same issue, so I reckon this might still pop up in the future. Did you ever manage to get premake5.exe to produce an .sln file and were you able to compile it on Visual Studio?

I gather the answer to both of those is no but I wanted to double check.

**Comment by dgcbritto** [comment] 2018-06-05 16:37
As far as I could understand, I couldn't go through any of the steps that you indicated. I got stuck while trying to run "msbuild SpookyHash.sln" which displayed an error message. Then I stopped.


________________________________
De: Mauricio Caceres Bravo <notifications@github.com>
Enviado: terça-feira, 5 de junho de 2018 13:33
Para: mcaceresb/stata-gtools
Cc: dgcbritto; Author
Assunto: Re: [mcaceresb/stata-gtools] Could not load plugin: c:\ado\plus\g\gtools_windows.plugin (#35)


No worries. I'm glad it's working on your end.

@ppoppitz<https://github.com/ppoppitz> was experiencing the same issue, so I reckon this might still pop up in the future. Did you ever manage to get premake5.exe to produce an .sln file and were you able to compile it on Visual Studio?

I gather the answer to both of those is no but I wanted to double check.

**Comment by dgcbritto** [comment] 2018-06-05 16:38
sorry, I got stuck at the first command "premake5.exe vs2013" which did not seem to go through

________________________________
De: Mauricio Caceres Bravo <notifications@github.com>
Enviado: terça-feira, 5 de junho de 2018 13:33
Para: mcaceresb/stata-gtools
Cc: dgcbritto; Author
Assunto: Re: [mcaceresb/stata-gtools] Could not load plugin: c:\ado\plus\g\gtools_windows.plugin (#35)


No worries. I'm glad it's working on your end.

@ppoppitz<https://github.com/ppoppitz> was experiencing the same issue, so I reckon this might still pop up in the future. Did you ever manage to get premake5.exe to produce an .sln file and were you able to compile it on Visual Studio?

I gather the answer to both of those is no but I wanted to double check.

**Comment by mcaceresb** [comment] 2018-06-22 22:32
Thanks for keeping me up to date.

1. Just in case, it might be a good idea to try the versions that worked for me. Can you clean the build and run:

```
git checkout 2c27b43
premake5.exe vs2013
```

with `msbuild SpookyHash.sln` after?

2. Does

```
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Com
mon7\IDE\VC\VCTargets\Platforms\x64\Platform.targets
```

exists? If not, the community version of VS might be lacking some components. Not 100% what to DL. Will keep looking into it.

**Comment by ppoppitz** [comment] 2018-06-25 17:46
(1)
running `premake ...` after  `checkout ...` I get an error message because git is missing on the server
```
Error: C:/Users/bued3667/gtest/spookyhash/build/premake5.lua:37: attempt to compare number with nil
```
after deleting the git check in lines `35-37` I get a SpookyHash.sln file.  `msbuild` then complains about the missing files under 
```
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Platforms\Win32\Platform.targets
```
(2)
The reason is of course that files & directories exist only until:
```
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets
```

**Comment by mcaceresb** [comment] 2018-07-07 14:38
Good to hear! @dgcbritto are you still experiencing the issue? You can update state via `update all`, I think. Then re-install gtools.

**Comment by dgcbritto** [comment] 2018-07-07 15:22
It has been working fine for me in the last couple of months. Thanks!
________________________________
De: Mauricio Caceres Bravo <notifications@github.com>
Enviado: sábado, 7 de julho de 2018 11:38:37
Para: mcaceresb/stata-gtools
Cc: dgcbritto; Mention
Assunto: Re: [mcaceresb/stata-gtools] Could not load plugin: c:\ado\plus\g\gtools_windows.plugin (#35)


Good to hear! @dgcbritto<https://github.com/dgcbritto> are you still experiencing the issue? You can update state via update all, I think. Then re-install gtools.

**Comment by mcaceresb** [comment] 2018-07-18 12:40
1. Are you also on Windows server 2016? Can you run

```stata
which gtools
dir c:\ado\plus\g\*gtools*
dir c:\ado\plus\s\*spooky*

adopath
disp "`c(sysdir_plus)'"
disp "`c(sysdir_personal)'"
```

2. Can you download download test.do, test1.plugin, test2.plugin, and spookyhash.dll from [here](https://github.com/mcaceresb/stata-gtools/tree/develop/src/github-issues/35). Then try to run test.do.

**Comment by dtetley001** [comment] 2018-07-18 12:48
1. Windows Server 2008 R2 Enterprise

 which gtools
C:\ado\plus\g\gtools.ado
*! version 0.13.1 02May2018 Mauricio Caceres Bravo, mauricio.caceres.bravo@gmail.com
*! Program for managing the gtools package installation

. 
. dir c:\ado\plus\g\*gtools*
   5.3k   7/18/18  8:05  gtools.ado        
   4.4k   7/18/18  8:05  gtools.sthlp      
 233.9k   7/18/18  8:05  gtools_macosx.plugin
 228.3k   7/18/18  8:05  gtools_unix.plugin
 401.3k   7/18/18  8:05  gtools_windows.plugin

. 
. dir c:\ado\plus\s\*spooky*
  18.5k   7/18/18  8:05  spookyhash.dll    

. 
. 
. 
. adopath
  [1]  (BASE)      "C:\Program Files (x86)\Stata15\ado\base/"
  [2]  (SITE)      "C:\Program Files (x86)\Stata15\ado\site/"
  [3]              "."
  [4]  (PERSONAL)  "c:\users\dustin\ado/"
  [5]  (PLUS)      "C:\ado\plus/"
  [6]  (OLDPLACE)  "c:\ado/"
  [7]              "D:\data\cairo\data\central repository for ado files"
  [8]              "D:\data\central_repository\ado_files"

. 
. disp "`c(sysdir_plus)'"
C:\ado\plus/

. 
. disp "`c(sysdir_personal)'"
c:\users\dustin\ado/

2. I will give that a try

**Comment by mcaceresb** [comment] 2018-07-18 13:31
Do you have access to Visual Studio?

**Comment by dtetley001** [comment] 2018-07-18 13:33
Not that I'm aware of

**Comment by mcaceresb** [comment] 2018-07-18 13:41
As best I can tell, this issue comes down to Windows being unable to load `spookyhash.dll`. I think it might be possible to fix this problem by compiling `spookyhash.dll` on a Windows Server machine (hopefully this would fix it on every Windows Server version).

I don't have access to Windows server, and is is unlikely that I'll be able to access a physical machine soon. If you (or someone else) can't compile `spookyhash.dll` for me then I can't fix this issue.

Apologies; I wish I could offer more help.

**Comment by tanby91** [comment] 2018-10-17 22:29
Hi, I apologize if I'm posting this in the wrong place, but I'm encountering the same issue on Windows 10 Pro 64bit using Stata 14.2 SE.

The error message is "Could not load plugin: c:\ado\plus\g\gtools_windows_v3.plugin"

I went back to Stata 13.1 to try using at, and there was a similar error message - "Could not load plugin: c:\ado\plus\g\gtools_windows_v2.plugin".

**Comment by mcaceresb** [comment] 2018-10-17 23:55
@tanby91 This is the correct place to ask; I'm sorry it's not working for you. Let's check that it is, in fact, the same problem: Can you download, to the same folder, test.do, test1.plugin, test2.plugin, and spookyhash.dll from [here](https://github.com/mcaceresb/stata-gtools/tree/develop/src/github-issues/35)? Then try to run test.do.

Let me know how that goes. I'm going to check if my uni has Windows 10 Pro installed anywhere; hopefully I can replicate this on a physical machine.

**Comment by tanby91** [comment] 2018-10-17 23:59
I get the following:


. program test1, plugin using(test1.plugin) 

. plugin call test1
Hello World

. 
. program test2, plugin using(test2.plugin) 
Could not load plugin: .\test2.plugin

**Comment by houtanb** [comment] 2019-01-02 21:35
@mcaceresb first off, thanks so much for your work on this project. It's really helping us out a lot for a side project I'm working on.

I'm planning on distributing some Stata code that depends on `gtools` and would like to make sure it works on all Windows machines. So, thinking about this bug, I was wondering if you can avoid the `spookyhash.dll` problem by either compiling against the static library or even by simply compiling the `spookyhash` source code directly into `gtools`?

I went ahead and recompiled `test2` above against `spookyhash.dll` (from `origin/master`) and against the spookyhash source code itself (with no library linked to the plugin). I put the code here: http://www.dynare.org/houtan/gtools/

I was wondering if perhaps you could recompile it using the Makefile provided and then ask one of the users here who has a version of Windows to test it? (I'm guessing they'll trust an executable provided by you before they'll trust one provided by me).

One note: I'm not a Windows pro, so was not able to compile against the static library. It seems as though the `spookyhash.lib` is not in ELF format and hence can't be complied with `x86_64-w64-mingw32-gcc.exe` (to be clear, I am talking of the `.lib` file created by the static build of `spookyhash`, not the `.lib` import library created by the dynamic build). Perhaps you know a way around this? I'd need to look into what flags to pass to Visual Studio to create the properly formatted library. Of course, unless the `spookyhash` library becomes a larger project, simply compiling the source code directly into the plugin should suffice.

Again, thanks for all your help on this

**Comment by mcaceresb** [comment] 2019-01-05 00:37
@houtanb I've tried compiling against a static library and haven't had much luck on Windows (the Linux and OSX versions compile against a static spookyhash). 

I do like the idea of trying to compile spookyhash as part of the `.pluign`; I'll add it to my TODO list and fiddle with it.

**Comment by mcaceresb** [comment] 2019-01-06 06:09
@houtanb If I did this correctly, I merged your pull request and fixed up the make script. Install from branch `develop-spooky-builtin` and test it out.

**Comment by houtanb** [comment] 2019-01-06 15:44
@mcaceresb thanks so much. We only have one computer where we can reproduce the error. I'll test that this week and get back to you.

**Comment by karldw** [comment] 2019-01-18 23:34
@mcaceresb, this worked for me. Thanks!

**Comment by mcaceresb** [comment] 2019-01-20 00:02
Good to know this issue might be fixed.

@houtanb Did you have a chance to test it out? Compiling spookyhash directly with the plugin doesn't seem to affect gtools in any other way so it will probably make it to master, but if it didn't work for you perhaps there is something else we can try before that.

**Comment by houtanb** [comment] 2019-01-20 13:39
@mcaceresb my colleague has been busy with other things and has unfortunately not had the time to test it. I will be sure to let you know once he does (hopefully soon)

**Comment by houtanb** [comment] 2019-01-20 13:41
It would be create if @dgcbritto @ppoppitz @dtetley001 and @tanby91 could test it too, if they still have access to the machines where the bug was encountered...

**Comment by ppoppitz** [comment] 2019-01-20 14:01
Thanks for all your work, will test when I have time in about one week.

Am 20. Januar 2019 14:41:31 MEZ schrieb Houtan Bastani <notifications@github.com>:

**Comment by houtanb** [comment] 2019-01-21 10:20
@mcaceresb, just FYI, we tested it and the change works for us.

**Comment by fink42** [comment] 2019-01-23 06:43
I have also been having this problem on both a Windows Server 2012 and a Windows 10 Pro.
What should I do to check whether the current fix solves my specific problem?
I tried uninstalling gtools and then:
`net install gtools, from(https://raw.githubusercontent.com/mcaceresb/stata-gtools/develop/build/)`

But I am still getting the same error:
` Could not load plugin: c:\ado\plus\e\env_set_windows_v3.plugin`

**Comment by mcaceresb** [comment] 2019-01-23 15:42
```
net uninstall gtools
net install gtools, from(https://raw.githubusercontent.com/mcaceresb/stata-gtools/develop/build/)
```

Start a new session; make sure `which gtools` gives version `1.2.7` and that `findfile spookyhash.dll` returns an error. If it still fails to load then the change isn't working for some reason.

**Comment by fink42** [comment] 2019-01-24 06:36
I tried the above. Uninstalling and installing from the developer branch goes smooth and the installed version is 1.2.7.
Running the command `findfile spookyhash.dll` returns `file "spookyhash.dll" not found`.
But I'm still getting `Could not load plugin: c:\ado\plus\e\env_set_windows_v3.plugin`

I'm happy to help in any way possible. I have access to Visual Studio on the Windows 10 Pro machine, if that could be helpful.

**Comment by mcaceresb** [comment] 2019-01-24 22:43
Interesting. I'll be merging this change to master in the future, since some people reported this fixed worked, but I won't close this issue. 

@fink42 Do you have cygwin installed? It might be easier to try it that way. If you don't, then can you follow the steps in [this comment](https://github.com/mcaceresb/stata-gtools/issues/35#issuecomment-389651279)?

**Comment by ppoppitz** [comment] 2019-01-25 09:31
running fine here. thanks again.

**Comment by fink42** [comment] 2019-01-25 09:42
Perfect!
When the fix is available by SSC I will test on the Windows Server 2012.

@mcaceresb I don't have cygwin. Will try generating a new spookyhash.dll following the guide from the comment. I vaguely remember trying it previously with a failing build as a result. Will give it a new shot and return with the results.

**Comment by fink42** [comment] 2019-01-25 11:22
I managed to build a new spookyhash.dll.
I'm not quite sure what then to do with it?

**Comment by fink42** [comment] 2019-01-25 12:17
@mcaceresb I tried installing via SSC and then replacing the spookyhash.dll, but the problem still persist. I might mention that the laptop is issued by a university. I have previously encountered certain applications and permissions being "blocked" by the IT administrators. They might have changed something with the latest version of Windows that causes gtools to fail, as it works fine on another university laptops running an older version of Windows 10.

I will contact the IT administrators and explain that it works on my colleague’s laptop but not on mine. They might know something which I don't

**Comment by BenjoSilver** [comment] 2019-02-04 19:43
@mcaceresb  Having the same problem. I can not load gtools after installing. I have the latest R version.
the error says 

> load('gtools')
Error in readChar(con, 5L, useBytes = TRUE) : cannot open the connection
In addition: Warning message:
In readChar(con, 5L, useBytes = TRUE) :
  cannot open compressed file 'gtools', probable reason 'No such file or directory'

My gtools version

gtools       NA                    NA        NA     "yes"            "3.5.2"

**Comment by mcaceresb** [comment] 2019-02-04 19:48
@BenjoSilver I believe you are looking for the R package of the same name. This repo is about a Stata plugin called `gtools`. I was unaware of the identically named R package.

Good luck with the error (I should point out that I believe R's gtools is up to 3.8 these days. Maybe upgrading will help?)

**Comment by BenjoSilver** [comment] 2019-02-04 20:38
@mcaceresb Thanks a bunch!

I did what you proposed. But it didn't help.

> install.packages("gtools")
trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.5/gtools_3.8.1.zip'
Content type 'application/zip' length 325812 bytes (318 KB)
downloaded 318 KB

package ‘gtools’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\...\AppData\Local\Temp\Rtmp0G5NNg\downloaded_packages

> load('gtools')
Error in readChar(con, 5L, useBytes = TRUE) : cannot open the connection
In addition: Warning message:
In readChar(con, 5L, useBytes = TRUE) :
  cannot open compressed file 'gtools', probable reason 'No such file or directory'

**Comment by mcaceresb** [comment] 2019-02-04 23:16
@BenjoSilver By the way your error is trying to use `load(gtools)` instead of `library(gtools)`, The latter loads the pacakge called `gtools`, the former tries to load an R object, which does not exist.

**Comment by mcaceresb** [comment] 2019-02-10 16:37
@fink42 I'm closing this issue since it seems to be fixed for several people and following this thread is very confusing. If you still experience it please open anew bug report with the details.

**Closed** 2019-02-10 19:05 UTC
Labels: bug
